name: Unity Tests on Sui Localnet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    services:
      sui-localnet:
        image: rust:1.78
        options: --privileged
        env:
          RUST_LOG: "off,sui_node=info"
        volumes:
          - /tmp/sui:/tmp/sui
        ports:
          - 8080:8080

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Rust
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        source $HOME/.cargo/env

    - uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - uses: actions/cache@v2
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-index-

    - name: Install Sui from Cargo
      run: |
        cargo install --locked --git https://github.com/MystenLabs/sui.git --branch testnet sui

    - name: Start Sui Localnet
      run: |
        sui start --with-faucet --force-regenesis

    - uses: actions/cache@v2
      with:
        path: Library
        key: ${{ runner.os }}-unity-library-${{ hashFiles('**/Packages/manifest.json') }}
        restore-keys: |
          ${{ runner.os }}-unity-library-

    - uses: game-ci/unity-test-runner@v4
      id: tests
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        unityVersion: 2021.3.6f1
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        testMode: PlayMode
        customParameters: -quit -batchmode -nographics -excludeCategory ExcludeFromCI -testResults /tmp/test-results.xml

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: /tmp/test-results.xml
