name: Unity Tests on Sui Localnet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    services:
      sui-localnet:
        image: rust:1.80.0
        options: --privileged
        env:
          RUST_LOG: "off,sui_node=info"
        volumes:
          - /tmp/sui:/tmp/sui
        ports:
          - 8080:8080

    steps:
    - uses: actions/checkout@v2
    
    - name: Download and Extract Sui Binaries
      run: |
        wget https://github.com/MystenLabs/sui/releases/download/testnet-v1.30.1/sui-testnet-v1.30.1-ubuntu-x86_64.tgz -O sui.tgz
        mkdir -p ~/sui
        tar -xzf sui.tgz -C ~/sui
        
    - name: Execute Sui Localnet
      run: |
        cd ~/sui
        ./sui start --with-faucet --force-regenesis &
        
    - name: Test Gas Price Reference
      run: |
        curl -v -H "Content-Type: application/json" -d '{"id":1,"method":"suix_getLatestSuiSystemState","jsonrpc":"2.0"}' "http://127.0.0.1:9000/" -X POST ;

#    - name: Start Sui Localnet
#      run: |
#        sui start --with-faucet --force-regenesis

#    - uses: actions/cache@v2
#      with:
#        path: Library
#        key: ${{ runner.os }}-unity-library-${{ hashFiles('**/Packages/manifest.json') }}
#        restore-keys: |
#          ${{ runner.os }}-unity-library-
#
#    - uses: game-ci/unity-test-runner@v4
#      id: tests
#      env:
#        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
#        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
#      with:
#        unityVersion: 2021.3.6f1
#        githubToken: ${{ secrets.GITHUB_TOKEN }}
#        testMode: PlayMode
#        customParameters: -quit -batchmode -nographics -excludeCategory ExcludeFromCI -testResults /tmp/test-results.xml
#
#    - uses: actions/upload-artifact@v2
#      if: always()
#      with:
#        name: test-results
#        path: /tmp/test-results.xml
